name: Android app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android_build:
    runs-on: macos-latest
    name: Android build

    steps:
    - uses: actions/checkout@v2
    - name: Build Titanium Android app
      uses:  m1ga/titanium-android-build@1.0.0
      with:
        version: 11.1.1.GA
